# Generated by Django 3.1 on 2020-08-31 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200830_1823'),
        ('courses', '0003_auto_20200830_1817'),
    ]

    operations = [
    ]
